### ISSUE TITLE
build of iconv module on node 0.8.x, "Cannot find module 'iconv'"

### ISSUE THREAD

**Issue by narf** [bnoordhuis/node-iconv#34]
I have a problem since I updated node to 0.8.x, node don't seem to find the module, here is the différence between 0.6.x and 0.8.x npm compilation output

node 0.6.x && npm 1.1.34

> iconv@1.2.1 install /srv/besyde/node_modules/as-besyde-server/node_modules/iconv
> node-gyp rebuild
> 
> info it worked if it ends with ok 
> spawn python [ '/root/.node-gyp/0.6.18/tools/gyp_addon',
>   'binding.gyp',
>   '-I/srv/besyde/node_modules/as-besyde-server/node_modules/iconv/build/config.gypi',
>   '-f',
>   'make' ]
> spawn make [ 'BUILDTYPE=Release', '-C', 'build' ]
> make: Entering directory `/srv/besyde/node_modules/as-besyde-server/node_modules/iconv/build'
>   CC(target) Release/obj.target/iconv/deps/libiconv/libcharset/lib/localcharset.o
> ../deps/libiconv/libcharset/lib/localcharset.c: In function ‘get_charset_aliases’:
> ../deps/libiconv/libcharset/lib/localcharset.c:176: warning: implicit declaration of function ‘fdopen’
> ../deps/libiconv/libcharset/lib/localcharset.c:176: warning: assignment makes pointer from integer without a cast
> CC(target) Release/obj.target/iconv/deps/libiconv/lib/iconv.o
> CXX(target) Release/obj.target/iconv/iconv.o
> SOLINK_MODULE(target) Release/obj.target/iconv.node
> SOLINK_MODULE(target) Release/obj.target/iconv.node: Finished
> COPY Release/iconv.node
> make: Leaving directory '/srv/besyde/node_modules/as-besyde-server/node_modules/iconv/build'
> info done ok 
> iconv@1.2.1 /srv/besyde/node_modules/as-besyde-server/node_modules/iconv

0.8.x  && npm 1.1.21

> iconv@1.2.1 install /home/vnoel/git/as-besyde-server/node_modules/iconv
> node-gyp rebuild
> 
> make: entrant dans le répertoire « /home/vnoel/git/as-besyde-server/node_modules/iconv/build »
> CC(target) Debug/obj.target/iconv/deps/libiconv/libcharset/lib/localcharset.o
> CC(target) Debug/obj.target/iconv/deps/libiconv/lib/iconv.o
> CXX(target) Debug/obj.target/iconv/iconv.o
> SOLINK_MODULE(target) Debug/obj.target/iconv.node
> SOLINK_MODULE(target) Debug/obj.target/iconv.node: Finished
> COPY Debug/iconv.node
> make: quittant le répertoire « /home/vnoel/git/as-besyde-server/node_modules/iconv/build »
> iconv@1.2.1 /home/vnoel/git/as-besyde-server/node_modules/iconv
