### ISSUE TITLE
Error while trying to install on OS X 10.10.5.

### ISSUE THREAD

**Issue by aprescott** [bnoordhuis/node-iconv#133]
I seem to be unable to install iconv on OS X 10.10.5.

```
~$ V=1 npm install -g iconv
-
> iconv@2.1.10 install /usr/local/lib/node_modules/iconv
> node-gyp rebuild

  cc '-DNODE_GYP_MODULE_NAME=libiconv' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DICONV_CONST=const' '-DENABLE_EXTRA=1' '-DHAVE_WORKING_O_NOFOLLOW=1' -I/Users/adamprescott/.node-gyp/0.12.7/src -I/Users/adamprescott/.node-gyp/0.12.7/deps/uv/include -I/Users/adamprescott/.node-gyp/0.12.7/deps/v8/include -I../deps/libiconv/srclib -I../support  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wendif-labels -Wno-unused-parameter -Wno-parentheses-equality -Wno-static-in-inline -Wno-tautological-compare -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/libiconv/deps/libiconv/lib/iconv.o.d.raw  -c -o Release/obj.target/libiconv/deps/libiconv/lib/iconv.o ../deps/libiconv/lib/iconv.c
  rm -f Release/iconv.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/iconv.a Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  c++ '-DNODE_GYP_MODULE_NAME=iconv' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/adamprescott/.node-gyp/0.12.7/src -I/Users/adamprescott/.node-gyp/0.12.7/deps/uv/include -I/Users/adamprescott/.node-gyp/0.12.7/deps/v8/include -I../node_modules/nan -I../support  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -Wall -Wextra -Wno-unused-parameter -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/iconv/src/binding.o.d.raw  -c -o Release/obj.target/iconv/src/binding.o ../src/binding.cc
  c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/iconv.node Release/obj.target/iconv/src/binding.o Release/iconv.a 
clang: error: no such file or directory: 'Release/iconv.a'
make: *** [Release/iconv.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/iconv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "iconv"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/adamprescott/npm-debug.log
```

```
⚡ ~$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

```
~$ cc -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by bnoordhuis** [comment]
I don't know what the issue is, the file it's complaining about is freshly created two lines up.  What does `find build` print afterwards?

**Comment by aprescott** [comment]
Well it's a `-g` install so it (correctly?) finds nothing because I'm in `~`. But when I do this as a non-`-g` install in the actual project I'm trying to get working (a Hubot copy), I get:

```
$ V=1 npm install iconv
# same error as above
$ find build
build
build/config.gypi
```

And `config.gypi`'s contents:

```
$ cat build/config.gypi 
# Do not edit. File was generated by node-gyp's "configure" step
{
  "target_defaults": {
    "cflags": [],
    "default_configuration": "Release",
    "defines": [],
    "include_dirs": [],
    "libraries": []
  },
  "variables": {
    "clang": 1,
    "host_arch": "x64",
    "icu_small": "false",
    "node_install_npm": "false",
    "node_prefix": "/usr/local/Cellar/node/0.12.7_1",
    "node_shared_cares": "false",
    "node_shared_http_parser": "false",
    "node_shared_libuv": "false",
    "node_shared_openssl": "false",
    "node_shared_v8": "false",
    "node_shared_zlib": "false",
    "node_tag": "",
    "node_use_dtrace": "true",
    "node_use_etw": "false",
    "node_use_mdb": "false",
    "node_use_openssl": "true",
    "node_use_perfctr": "false",
    "openssl_no_asm": 0,
    "python": "/usr/bin/python",
    "target_arch": "x64",
    "uv_library": "static_library",
    "uv_parent_path": "/deps/uv/",
    "uv_use_dtrace": "true",
    "v8_enable_gdbjit": 0,
    "v8_enable_i18n_support": 0,
    "v8_no_strict_aliasing": 1,
    "v8_optimized_debug": 0,
    "v8_random_seed": 0,
    "v8_use_snapshot": "true",
    "want_separate_host_toolset": 0,
    "nodedir": "/Users/adamprescott/.node-gyp/0.12.7",
    "copy_dev_lib": "true",
    "standalone_static_library": 1
  }
}
```

**Comment by bnoordhuis** [comment]
Are you using the node + npm + node-gyp from homebrew?  What happens when you use the official binaries from nodejs.org?  I'm somewhat distrustful of how homebrew packages up node and npm, I've gotten bug reports about it before.

**Comment by hustcer** [comment]
I got a similar error, can anyone help me?:
```bash
-
> iconv@2.1.10 install /Users/hustcer/github/star/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/iconv.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/iconv.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/hustcer/github/star/node_modules/iconv
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.1.0
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.1.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hustcer/github/star/npm-debug.log
```

**Comment by bnoordhuis** [comment]
@hustcer That's an unrelated issue that people have been experiencing after upgrading xcode.  Make sure you upgrade both xcode and the xcode command line tools.  You may also have to do a full software update.

**Comment by hustcer** [comment]
@bnoordhuis I see, Thanks.

**Comment by aprescott** [comment]
> Are you using the node + npm + node-gyp from homebrew? What happens when you use the official binaries from nodejs.org? I'm somewhat distrustful of how homebrew packages up node and npm, I've gotten bug reports about it before.

I am indeed using homebrew for node (and thus npm). I'm not sure about node-gyp, though. Would homebrew install its own node-gyp, instead of it being installed through an `npm install` like any other package? (Sorry if that's a stupid question, I'm not too familiar with specific node/npm details like this.)

I would ideally like to avoid installing the binaries for node outside of homebrew, since then I'm maintaining the install outside the package manager. Is there any way I could diagnose what the issue is? Are there specific things you've seen cause problems with homebrew that I could look into? Happy to provide details about the system environment.

**Comment by aprescott** [comment]
I tried building this from `master` just for kicks.

I found two things. First, it looks like the README instructions of `git clone` followed by `node-gyp configure build` don't work for me, using node v0.12.7 and node-gyp 3.0.3. It was complaining about `nan` being missing:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
```

So first I had to do `npm install nan`.

After that, I got the same error as in my original PR comment, but from `node-gyp configure build` directly. One difference is that, here, it's using node-gyp 3.0.3, whereas `npm install -g iconv` uses, as per my original PR comment, node-gyp 2.0.2. So I guess this shows it doesn't work with 3.0.3 _or_ 2.0.2.

```
$ V=1 node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.12.7 | darwin | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/private/tmp/node-iconv/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/adamprescott/.node-gyp/0.12.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/adamprescott/.node-gyp/0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/private/tmp/node-iconv',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  rm -f Release/iconv.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/iconv.a Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/iconv.node Release/obj.target/iconv/src/binding.o Release/iconv.a 
clang: error: no such file or directory: 'Release/iconv.a'
make: *** [Release/iconv.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /private/tmp/node-iconv
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

**Comment by aprescott** [comment]
Haha, hmmmm, this is telling:

```
/tmp/node-iconv/build::master$ head gyp-mac-tool 
#!/usr/bin/env python
# Generated by gyp. Do not edit.
# Copyright (c) 2012 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Utility functions to perform Xcode-style build steps.

These functions are executed via gyp-mac-tool when using the Makefile generator.
"""
/tmp/node-iconv/build::master$ /usr/bin/env python
/tmp/node-iconv/build::master$ which python
/Users/adamprescott/bin/python
/tmp/node-iconv/build::master$ /usr/bin/env python -v
/tmp/node-iconv/build::master$ python -v
```

**Comment by aprescott** [comment]
`rm ~/bin/python` fixed this. I have absolutely no idea how I haven't hit this problem before, or why on Earth there's an empty `~/bin/python` in my system. But there we go! Sorry for the time spent on this.

**Comment by bnoordhuis** [comment]
I've updated the build instructions in 4fad2dc, thanks for pointing that out.
