### ISSUE TITLE
v2.1.3 fails to build on OS X (10.9)

### ISSUE THREAD

**Issue by awk** [bnoordhuis/node-iconv#92]
```
npm install iconv
npm http GET https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> iconv@2.1.3 install /Users/awk/iconv_test/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
../src/binding.cc:120:3: error: class member cannot be redeclared
  NAN_WEAK_CALLBACK(WeakCallback)
  ^
../node_modules/nan/nan.h:1426:28: note: expanded from macro 'NAN_WEAK_CALLBACK'
    static NAN_INLINE void _Nan_Weak_Callback_ ## name(                        \
                           ^
<scratch space>:83:1: note: expanded from here
_Nan_Weak_Callback_WeakCallback
^
../src/binding.cc:120:3: note: previous declaration is here
../node_modules/nan/nan.h:1414:28: note: expanded from macro 'NAN_WEAK_CALLBACK'
    static NAN_INLINE void _Nan_Weak_Callback_ ## name(                        \
                           ^
<scratch space>:81:1: note: expanded from here
_Nan_Weak_Callback_WeakCallback
^
1 error generated.
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/awk/iconv_test/node_modules/iconv
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! iconv@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.3 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "iconv"
npm ERR! cwd /Users/awk/iconv_test
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/awk/iconv_test/npm-debug.log
npm ERR! not ok code 0
```
