### ISSUE TITLE
npm install fails on node 12.3.0

### ISSUE THREAD

**Issue by HaroldStruwig** [bnoordhuis/node-iconv#200]
this was working on node 12.1.0 but now fails on 12.3.0

log:
```
harold@ubuntu:~/git-repos-ext/node-iconv$ npm i

> iconv@2.3.4 install /home/harold/git-repos-ext/node-iconv
> node-gyp rebuild

make: Entering directory '/home/harold/git-repos-ext/node-iconv/build'
  CXX(target) Release/obj.target/iconv/src/binding.o
In file included from ../node_modules/nan/nan.h:54:0,
                 from ../src/binding.cc:18:
/home/harold/.node-gyp/12.3.0/include/node/node.h:107:12: fatal error: util-inl.h: No such file or directory
 #  include <util-inl.h>
            ^~~~~~~~~~~~
compilation terminated.
iconv.target.mk:111: recipe for target 'Release/obj.target/iconv/src/binding.o' failed
make: *** [Release/obj.target/iconv/src/binding.o] Error 1
make: Leaving directory '/home/harold/git-repos-ext/node-iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/harold/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/harold/.nvm/versions/node/v12.3.0/bin/node" "/home/harold/.nvm/versions/node/v12.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/harold/git-repos-ext/node-iconv
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.3.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.3.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harold/.npm/_logs/2019-05-22T14_05_11_882Z-debug.log
```

**Comment by bnoordhuis** [comment]
Upgrade to Node.js v12.3.1, that contains the fix, see https://github.com/nodejs/node/pull/27804.

(IOW, it's not a node-iconv issue; it affects all native modules.)
